// ALO Learning Journey — Own AI Agent Roster (40 agents)
// These are OUR agents (orchestrator + specialist agents). External inference
// providers (when configured) are only tools. The platform works without any
// paid key by using safe local fallback templates.

export type AgentStatus =
  | "active"
  | "idle"
  | "running"
  | "blocked_external_setup"
  | "error";

export type AgentCategory =
  | "orchestration"
  | "research"
  | "content"
  | "safety"
  | "media"
  | "publishing"
  | "community"
  | "learning"
  | "ops";

export interface AIAgent {
  id: string;
  name: string;
  role: string;
  description: string;
  category: AgentCategory;
  systemPrompt: string;
  tools: string[];
  permissions: string[];
  knowledgeScope: string[];
  memoryScope: string[];
  provider: "local" | "zai-llm" | "external-optional";
  model: string;
  status: AgentStatus;
  lastRunAt: string | null;
  lastError: string | null;
  retryCount: number;
  estimatedCostUsd: number;
}

const bn = "Bengali-first, warm, parenting-safe tone.";

export const AGENTS: AIAgent[] = [
  {
    id: "master_orchestrator",
    name: "MasterOrchestratorAgent",
    role: "Central brain",
    description:
      "Coordinates every other agent, decides the next pipeline step, and keeps the whole workflow under admin control.",
    category: "orchestration",
    systemPrompt: `You are the Master Orchestrator of ALO Learning Journey. ${bn} Route tasks to specialist agents, enforce Protective Mode before approval, and never publish without admin consent.`,
    tools: ["workflow.engine", "queue.engine", "approval.engine"],
    permissions: ["read:all", "write:agent_runs", "trigger:agents"],
    knowledgeScope: ["brand", "policies", "pipeline"],
    memoryScope: ["global", "session"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "active",
    lastRunAt: "2m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.012,
  },
  {
    id: "trend_research",
    name: "TrendResearchAgent",
    role: "Trend discovery",
    description:
      "Scans parenting & child-development topics trending in Bangladesh and surfaces safe, brand-aligned ideas.",
    category: "research",
    systemPrompt: `Find trending, safe parenting topics. ${bn} Never suggest fear-based or medical-claim topics.`,
    tools: ["web.search", "rag.search"],
    permissions: ["read:trends", "write:ideas"],
    knowledgeScope: ["trends", "parenting"],
    memoryScope: ["weekly"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "active",
    lastRunAt: "12m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.008,
  },
  {
    id: "topic_ideation",
    name: "TopicIdeationAgent",
    role: "Idea generation",
    description:
      "Turns trends into 3 concrete content ideas with hook angles and target audience per platform.",
    category: "research",
    systemPrompt: `Generate 3 distinct content ideas per topic. ${bn} Each idea must have a hook, angle and audience.`,
    tools: ["rag.search", "memory.recall"],
    permissions: ["write:ideas"],
    knowledgeScope: ["brand", "audience"],
    memoryScope: ["ideas"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "1h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.006,
  },
  {
    id: "rag_memory",
    name: "RAGMemoryAgent",
    role: "Retrieval",
    description:
      "Runs hybrid (keyword + semantic) retrieval over company-private knowledge and returns cited sources.",
    category: "research",
    systemPrompt: `Retrieve only from the current company's knowledge base. Always cite sources. ${bn}`,
    tools: ["rag.search", "rerank"],
    permissions: ["read:rag"],
    knowledgeScope: ["knowledge_base"],
    memoryScope: ["retrievals"],
    provider: "local",
    model: "local-hybrid-search",
    status: "active",
    lastRunAt: "just now",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "knowledge_indexer",
    name: "KnowledgeIndexerAgent",
    role: "Ingestion",
    description:
      "Ingests PDF/DOCX/CSV/URLs, chunks text, builds keyword index and stores embeddings for RAG.",
    category: "ops",
    systemPrompt: `Extract, chunk (≈300 tokens), index keywords and store embeddings. ${bn} Version every document.`,
    tools: ["file.extract", "chunker", "embedder"],
    permissions: ["write:rag"],
    knowledgeScope: ["ingestion"],
    memoryScope: ["index"],
    provider: "local",
    model: "local-indexer",
    status: "idle",
    lastRunAt: "3h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "research",
    name: "ResearchAgent",
    role: "Deep research",
    description:
      "Gathers supporting facts and citations for a chosen topic before any script is written.",
    category: "research",
    systemPrompt: `Collect verified facts with citations. ${bn} Reject unverified medical claims.`,
    tools: ["web.search", "rag.search"],
    permissions: ["read:web", "write:research"],
    knowledgeScope: ["facts"],
    memoryScope: ["research"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "5h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.009,
  },
  {
    id: "content_writer",
    name: "ContentWriterAgent",
    role: "Script writing",
    description:
      "Writes the master reel script plus platform-specific scripts (Shorts, long YouTube, etc.).",
    category: "content",
    systemPrompt: `Write clear, warm Bengali scripts with a strong 3-second hook. ${bn}`,
    tools: ["rag.search", "template.writer"],
    permissions: ["write:packages"],
    knowledgeScope: ["brand_voice"],
    memoryScope: ["scripts"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "active",
    lastRunAt: "8m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.01,
  },
  {
    id: "bn_brand_voice",
    name: "BengaliBrandVoiceAgent",
    role: "Voice & tone",
    description:
      "Ensures all Bengali copy matches the warm, non-judgmental আলো brand voice and correct grammar.",
    category: "content",
    systemPrompt: `Enforce the আলো brand voice: warm, hopeful, never shaming. ${bn} Fix Bengali grammar.`,
    tools: ["grammar.check", "tone.lint"],
    permissions: ["write:packages"],
    knowledgeScope: ["brand_voice"],
    memoryScope: ["voice"],
    provider: "local",
    model: "local-tone-linter",
    status: "active",
    lastRunAt: "8m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "safety_guardian",
    name: "SafetyGuardianAgent",
    role: "Protective Mode",
    description:
      "Runs Protective Mode on every artifact: child safety, medical claims, parent shaming, fear, deepfake risk, brand tone.",
    category: "safety",
    systemPrompt: `You are the Safety Guardian. Block unsafe content. ${bn} Add pediatrician disclaimer when needed.`,
    tools: ["safety.rules", "policy.check"],
    permissions: ["block:content", "write:safety_reviews"],
    knowledgeScope: ["safety_policy", "platform_policy"],
    memoryScope: ["violations"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "active",
    lastRunAt: "3m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.007,
  },
  {
    id: "fact_check",
    name: "FactCheckAgent",
    role: "Fact verification",
    description:
      "Verifies developmental & medical claims against RAG sources and flags unverified assertions.",
    category: "safety",
    systemPrompt: `Verify every factual claim. ${bn} Flag any guaranteed-outcome language.`,
    tools: ["rag.search", "claim.verify"],
    permissions: ["write:safety_reviews"],
    knowledgeScope: ["facts", "policy"],
    memoryScope: ["claims"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "20m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.006,
  },
  {
    id: "hook_optimizer",
    name: "HookOptimizerAgent",
    role: "Hook crafting",
    description:
      "Produces 3 viral-style hooks per topic tuned for 3-second retention on Reels/Shorts/TikTok.",
    category: "content",
    systemPrompt: `Write 3 scroll-stopping hooks (safe, curiosity-driven). ${bn}`,
    tools: ["template.hooks"],
    permissions: ["write:packages"],
    knowledgeScope: ["hooks"],
    memoryScope: ["hook_perf"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "15m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.005,
  },
  {
    id: "seo",
    name: "SEOAgent",
    role: "SEO keywords",
    description:
      "Generates Bengali + English SEO keywords, YouTube tags and search-friendly titles.",
    category: "content",
    systemPrompt: `Produce SEO keywords & titles for YouTube and Google. ${bn}`,
    tools: ["keyword.expand"],
    permissions: ["write:packages"],
    knowledgeScope: ["seo"],
    memoryScope: ["seo_perf"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "1h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.005,
  },
  {
    id: "caption",
    name: "CaptionAgent",
    role: "Captions",
    description:
      "Writes platform-specific captions (Facebook, Instagram, TikTok, LinkedIn, X, WhatsApp, Threads, Pinterest, Telegram).",
    category: "content",
    systemPrompt: `Write one caption per platform, tuned to its style. ${bn}`,
    tools: ["template.captions"],
    permissions: ["write:packages"],
    knowledgeScope: ["platforms"],
    memoryScope: ["caption_perf"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "1h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.006,
  },
  {
    id: "hashtag",
    name: "HashtagAgent",
    role: "Hashtags",
    description:
      "Builds platform-safe hashtag sets (mix of broad, niche, Bengali and English).",
    category: "content",
    systemPrompt: `Create safe hashtag sets per platform. ${bn} Avoid banned tags.`,
    tools: ["hashtag.db"],
    permissions: ["write:packages"],
    knowledgeScope: ["hashtags"],
    memoryScope: ["hashtag_perf"],
    provider: "local",
    model: "local-hashtag-db",
    status: "idle",
    lastRunAt: "1h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "image_prompt",
    name: "ImagePromptAgent",
    role: "Image prompts",
    description:
      "Crafts protective-mode-safe image prompts for every required platform size.",
    category: "media",
    systemPrompt: `Write image prompts that are child-safe, brand-aligned, no real faces unless consented. ${bn}`,
    tools: ["template.image_prompt"],
    permissions: ["write:packages"],
    knowledgeScope: ["brand_visual"],
    memoryScope: ["image_perf"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "45m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.004,
  },
  {
    id: "image_generator",
    name: "ImageGeneratorAgent",
    role: "Image generation",
    description:
      "Generates all platform image sizes; local poster first, configured provider as fallback.",
    category: "media",
    systemPrompt: `Generate images per platform size. Local-first. ${bn} Never overwrite originals.`,
    tools: ["image.gen", "image.resize"],
    permissions: ["write:assets"],
    knowledgeScope: ["sizes"],
    memoryScope: ["image_jobs"],
    provider: "external-optional",
    model: "image-gen (fallback: local-poster)",
    status: "blocked_external_setup",
    lastRunAt: "2h ago",
    lastError: "Provider key missing — using local placeholder generator.",
    retryCount: 1,
    estimatedCostUsd: 0.02,
  },
  {
    id: "family_identity",
    name: "FamilyIdentityAgent",
    role: "Character identity",
    description:
      "Manages brand family characters (Baby Girl, Mother, Father, Teacher, Narrator) and consent records.",
    category: "media",
    systemPrompt: `Maintain consistent character identities. ${bn} Require consent before any user-owned character.`,
    tools: ["character.db"],
    permissions: ["read:family", "write:family"],
    knowledgeScope: ["characters"],
    memoryScope: ["characters"],
    provider: "local",
    model: "local-character-db",
    status: "active",
    lastRunAt: "30m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "face_consistency",
    name: "FaceConsistencyAgent",
    role: "Face consistency",
    description:
      "Checks generated frames for face consistency against consented reference images.",
    category: "safety",
    systemPrompt: `Verify face consistency. Block drift. ${bn} Require face-consent before use.`,
    tools: ["face.compare"],
    permissions: ["block:assets"],
    knowledgeScope: ["faces"],
    memoryScope: ["face_checks"],
    provider: "local",
    model: "local-face-check",
    status: "idle",
    lastRunAt: "2h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "video_director",
    name: "VideoDirectorAgent",
    role: "Storyboard",
    description:
      "Builds storyboard, scene prompts and shot list from the approved script.",
    category: "media",
    systemPrompt: `Direct scenes: storyboard, shots, timing. ${bn} Keep within 30–60s.`,
    tools: ["storyboard.gen"],
    permissions: ["write:video_jobs"],
    knowledgeScope: ["directing"],
    memoryScope: ["storyboards"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "3h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.008,
  },
  {
    id: "video_generator",
    name: "VideoGeneratorAgent",
    role: "Video rendering",
    description:
      "Assembles master 9x16 video + platform exports. FFmpeg-local first, external provider fallback.",
    category: "media",
    systemPrompt: `Render master_9x16 + platform exports. ${bn} No publishing before approval.`,
    tools: ["ffmpeg", "video.gen"],
    permissions: ["write:videos"],
    knowledgeScope: ["video_specs"],
    memoryScope: ["video_jobs"],
    provider: "external-optional",
    model: "ffmpeg-local (fallback: provider)",
    status: "blocked_external_setup",
    lastRunAt: "3h ago",
    lastError: "FFmpeg probe missing in this env — queued as external_setup_required.",
    retryCount: 1,
    estimatedCostUsd: 0.08,
  },
  {
    id: "voice",
    name: "VoiceAgent",
    role: "Voice synthesis",
    description:
      "Generates warm Bangla mother/father/narrator/teacher voices. Local TTS first, provider fallback.",
    category: "media",
    systemPrompt: `Synthesize natural Bangla voice. ${bn} Never clone a real voice without consent.`,
    tools: ["tts.local", "tts.provider"],
    permissions: ["write:voice_assets"],
    knowledgeScope: ["voices"],
    memoryScope: ["voice_jobs"],
    provider: "external-optional",
    model: "local-tts (fallback: provider)",
    status: "blocked_external_setup",
    lastRunAt: "3h ago",
    lastError: "No TTS engine in this env — external_setup_required.",
    retryCount: 1,
    estimatedCostUsd: 0.03,
  },
  {
    id: "subtitle",
    name: "SubtitleAgent",
    role: "Subtitles & SRT",
    description:
      "Generates accurate Bengali subtitles, SRT file and burn-in safe margins.",
    category: "media",
    systemPrompt: `Produce accurate Bengali subtitles + SRT. ${bn} Readable, safe margins.`,
    tools: ["asr.align", "srt.gen"],
    permissions: ["write:subtitles"],
    knowledgeScope: ["subtitles"],
    memoryScope: ["subtitle_jobs"],
    provider: "local",
    model: "local-srt",
    status: "idle",
    lastRunAt: "3h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "thumbnail",
    name: "ThumbnailAgent",
    role: "Thumbnails",
    description:
      "Designs click-worthy but honest thumbnails with Bengali text and brand framing.",
    category: "media",
    systemPrompt: `Design honest, brand-safe thumbnails. ${bn} No clickbait faces.`,
    tools: ["image.compose"],
    permissions: ["write:assets"],
    knowledgeScope: ["thumbnails"],
    memoryScope: ["thumb_perf"],
    provider: "local",
    model: "local-thumbnail",
    status: "idle",
    lastRunAt: "3h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "platform_formatter",
    name: "PlatformFormatterAgent",
    role: "Platform sizing",
    description:
      "Ensures every asset meets exact platform dimensions and safe zones for all 11 platforms.",
    category: "media",
    systemPrompt: `Format assets to exact platform sizes & safe zones. ${bn}`,
    tools: ["image.resize", "video.transcode"],
    permissions: ["write:asset_variants"],
    knowledgeScope: ["sizes"],
    memoryScope: ["formats"],
    provider: "local",
    model: "local-formatter",
    status: "active",
    lastRunAt: "20m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "quality_critic",
    name: "QualityCriticAgent",
    role: "Quality scoring",
    description:
      "Scores content 0–100 on hook strength, clarity, brand fit, retention risk and CTA safety.",
    category: "safety",
    systemPrompt: `Score content quality 0–100 with reasons. ${bn} Be strict but constructive.`,
    tools: ["quality.score"],
    permissions: ["write:quality_reviews"],
    knowledgeScope: ["quality"],
    memoryScope: ["quality_history"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "active",
    lastRunAt: "5m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.006,
  },
  {
    id: "approval_preparer",
    name: "ApprovalPreparerAgent",
    role: "Approval packaging",
    description:
      "Bundles script, captions, images, voice, video and safety review into one admin-approval item.",
    category: "ops",
    systemPrompt: `Package the full content bundle for admin review. ${bn} Include safety + quality scores.`,
    tools: ["bundle.gen"],
    permissions: ["write:approval_queue"],
    knowledgeScope: ["pipeline"],
    memoryScope: ["bundles"],
    provider: "local",
    model: "local-bundler",
    status: "active",
    lastRunAt: "5m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "publisher",
    name: "PublisherAgent",
    role: "Publishing",
    description:
      "Publishes to connected platforms via official APIs, captures real post IDs and URLs.",
    category: "publishing",
    systemPrompt: `Publish only after admin approval. Capture real provider post IDs. ${bn} Never fake success.`,
    tools: ["publisher.*"],
    permissions: ["write:published_posts"],
    knowledgeScope: ["platforms"],
    memoryScope: ["publish_jobs"],
    provider: "local",
    model: "local-publisher-router",
    status: "idle",
    lastRunAt: "1h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "comment_moderation",
    name: "CommentModerationAgent",
    role: "Comment moderation",
    description:
      "Classifies inbox comments into safe / question / sensitive / spam / toxic and escalates.",
    category: "community",
    systemPrompt: `Classify and moderate comments. ${bn} Escalate medical & abuse-risk comments.`,
    tools: ["comment.classify"],
    permissions: ["read:comments", "write:comment_replies"],
    knowledgeScope: ["community"],
    memoryScope: ["comments"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "40m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.005,
  },
  {
    id: "community_reply",
    name: "CommunityReplyAgent",
    role: "Auto replies",
    description:
      "Drafts safe replies only for safe categories; flags sensitive ones for human response.",
    category: "community",
    systemPrompt: `Draft warm replies for safe comments only. ${bn} Never auto-reply to medical/abuse comments.`,
    tools: ["reply.draft"],
    permissions: ["write:comment_replies"],
    knowledgeScope: ["brand_voice"],
    memoryScope: ["replies"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "40m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.004,
  },
  {
    id: "analytics",
    name: "AnalyticsAgent",
    role: "Analytics collection",
    description:
      "Pulls views, reach, watch time, retention, shares, saves, leads from connected platforms.",
    category: "learning",
    systemPrompt: `Collect and normalize analytics per platform. ${bn} Store snapshots.`,
    tools: ["analytics.fetch"],
    permissions: ["read:analytics", "write:analytics_snapshots"],
    knowledgeScope: ["metrics"],
    memoryScope: ["analytics"],
    provider: "local",
    model: "local-analytics",
    status: "active",
    lastRunAt: "10m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "weekly_learning",
    name: "WeeklyLearningAgent",
    role: "Self-learning",
    description:
      "Every week analyses performance and recommends improvements (never auto-rewrites safety rules).",
    category: "learning",
    systemPrompt: `Produce weekly recommendations from performance data. ${bn} Never rewrite safety rules automatically.`,
    tools: ["stats.analyze"],
    permissions: ["write:weekly_reports"],
    knowledgeScope: ["performance"],
    memoryScope: ["learnings"],
    provider: "zai-llm",
    model: "glm-4.6",
    status: "idle",
    lastRunAt: "2d ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.01,
  },
  {
    id: "telegram",
    name: "TelegramAgent",
    role: "Telegram bot",
    description:
      "Handles admin Telegram commands (/ideas, /approve, /publish, /emergency_stop …) with allow-list.",
    category: "ops",
    systemPrompt: `Execute only allow-listed admin chat IDs. ${bn} Send daily report.`,
    tools: ["telegram.api"],
    permissions: ["read:all", "write:commands"],
    knowledgeScope: ["commands"],
    memoryScope: ["telegram"],
    provider: "local",
    model: "local-telegram",
    status: "active",
    lastRunAt: "1m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "cost_router",
    name: "CostRouterAgent",
    role: "Cost routing",
    description:
      "Routes inference to local models first; uses paid providers only when justified by cost ceiling.",
    category: "ops",
    systemPrompt: `Minimize cost: local first, paid only when needed. ${bn} Track spend per agent.`,
    tools: ["cost.track"],
    permissions: ["read:costs"],
    knowledgeScope: ["costs"],
    memoryScope: ["spend"],
    provider: "local",
    model: "local-cost-router",
    status: "active",
    lastRunAt: "just now",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "retry_recovery",
    name: "RetryRecoveryAgent",
    role: "Retry & backoff",
    description:
      "Retries transient provider failures with exponential backoff; stops on permanent errors.",
    category: "ops",
    systemPrompt: `Retry transient errors with backoff. Stop on 4xx permanent errors. ${bn}`,
    tools: ["retry.queue"],
    permissions: ["write:agent_runs"],
    knowledgeScope: ["errors"],
    memoryScope: ["retries"],
    provider: "local",
    model: "local-retry",
    status: "active",
    lastRunAt: "2m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "audit_security",
    name: "AuditSecurityAgent",
    role: "Audit & security",
    description:
      "Writes audit logs for every admin action, secrets access, and cross-tenant access attempts.",
    category: "ops",
    systemPrompt: `Log every privileged action. ${bn} Never log raw secrets.`,
    tools: ["audit.log"],
    permissions: ["write:audit_logs"],
    knowledgeScope: ["security"],
    memoryScope: ["audit"],
    provider: "local",
    model: "local-audit",
    status: "active",
    lastRunAt: "just now",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "backup",
    name: "BackupAgent",
    role: "Backups",
    description:
      "Creates encrypted DB + storage backups on schedule and verifies restore integrity.",
    category: "ops",
    systemPrompt: `Backup DB + storage, encrypt, verify. ${bn} Keep retention window.`,
    tools: ["backup.create", "backup.verify"],
    permissions: ["write:backups"],
    knowledgeScope: ["backups"],
    memoryScope: ["backups"],
    provider: "local",
    model: "local-backup",
    status: "idle",
    lastRunAt: "12h ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "notification",
    name: "NotificationAgent",
    role: "Notifications",
    description:
      "Sends admin notifications (approvals, failures, token expiry, sensitive comments) via UI + Telegram.",
    category: "ops",
    systemPrompt: `Notify admin of approvals, failures, token expiry. ${bn}`,
    tools: ["notify.ui", "notify.telegram"],
    permissions: ["write:notifications"],
    knowledgeScope: ["events"],
    memoryScope: ["notifications"],
    provider: "local",
    model: "local-notifier",
    status: "active",
    lastRunAt: "3m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "oauth_health",
    name: "OAuthHealthAgent",
    role: "OAuth health",
    description:
      "Monitors token expiry & permission scopes across all connected platforms.",
    category: "ops",
    systemPrompt: `Monitor token expiry & scopes. ${bn} Warn before expiry.`,
    tools: ["oauth.check"],
    permissions: ["read:social"],
    knowledgeScope: ["oauth"],
    memoryScope: ["oauth"],
    provider: "local",
    model: "local-oauth-health",
    status: "active",
    lastRunAt: "5m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "token_refresh",
    name: "TokenRefreshAgent",
    role: "Token refresh",
    description:
      "Refreshes expiring OAuth tokens using stored refresh tokens; marks revoked ones for reconnection.",
    category: "ops",
    systemPrompt: `Refresh tokens before expiry. ${bn} Mark revoked as external_setup_required.`,
    tools: ["oauth.refresh"],
    permissions: ["write:social"],
    knowledgeScope: ["oauth"],
    memoryScope: ["tokens"],
    provider: "local",
    model: "local-token-refresh",
    status: "idle",
    lastRunAt: "30m ago",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
  {
    id: "queue_supervisor",
    name: "QueueSupervisorAgent",
    role: "Queue supervisor",
    description:
      "Runs cPanel-safe cron batches: max 10 light + 1–3 heavy jobs per run, with locks & timeouts.",
    category: "ops",
    systemPrompt: `Supervise cron batches: 10 light + 1–3 heavy per run. ${bn} Use locks & timeouts.`,
    tools: ["queue.lock", "batch.run"],
    permissions: ["read:queue", "write:agent_runs"],
    knowledgeScope: ["queue"],
    memoryScope: ["batches"],
    provider: "local",
    model: "local-queue-supervisor",
    status: "active",
    lastRunAt: "just now",
    lastError: null,
    retryCount: 0,
    estimatedCostUsd: 0.0,
  },
];

export const AGENT_CATEGORIES: { id: AgentCategory; label: string; bn: string }[] = [
  { id: "orchestration", label: "Orchestration", bn: "অর্কেস্ট্রেশন" },
  { id: "research", label: "Research & RAG", bn: "গবেষণা" },
  { id: "content", label: "Content", bn: "কনটেন্ট" },
  { id: "safety", label: "Protective Mode", bn: "নিরাপত্তা" },
  { id: "media", label: "Media", bn: "মিডিয়া" },
  { id: "publishing", label: "Publishing", bn: "প্রকাশনা" },
  { id: "community", label: "Community", bn: "কমিউনিটি" },
  { id: "learning", label: "Self-Learning", bn: "শেখা" },
  { id: "ops", label: "Operations", bn: "পরিচালনা" },
];
